// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('ESTADO DE TARGETA', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('ESTADO DE TARGETA', async function() {
    await driver.get("https://bincheck.io/")
    await driver.manage().window().setRect(1382, 744)
    await driver.findElement(By.id("bin")).click()
    await driver.findElement(By.id("bin")).sendKeys("5187 6171 4548 8586")
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.executeScript("window.scrollTo(0,890)")
    await driver.findElement(By.id("bin")).click()
    await driver.findElement(By.id("bin")).sendKeys("5187 6171 4540 4104")
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.id("bin")).click()
    await driver.findElement(By.id("bin")).sendKeys("5187 6171 4544 0488")
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.executeScript("window.scrollTo(0,769)")
  })
})
